// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sale.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddSaleitemReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Itemname             string   `protobuf:"bytes,2,opt,name=itemname,proto3" json:"itemname,omitempty"`
	Price                float32  `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSaleitemReq) Reset()         { *m = AddSaleitemReq{} }
func (m *AddSaleitemReq) String() string { return proto.CompactTextString(m) }
func (*AddSaleitemReq) ProtoMessage()    {}
func (*AddSaleitemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_983657353a4bf784, []int{0}
}

func (m *AddSaleitemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSaleitemReq.Unmarshal(m, b)
}
func (m *AddSaleitemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSaleitemReq.Marshal(b, m, deterministic)
}
func (m *AddSaleitemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSaleitemReq.Merge(m, src)
}
func (m *AddSaleitemReq) XXX_Size() int {
	return xxx_messageInfo_AddSaleitemReq.Size(m)
}
func (m *AddSaleitemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSaleitemReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddSaleitemReq proto.InternalMessageInfo

func (m *AddSaleitemReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddSaleitemReq) GetItemname() string {
	if m != nil {
		return m.Itemname
	}
	return ""
}

func (m *AddSaleitemReq) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type AddSaleitemRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSaleitemRsp) Reset()         { *m = AddSaleitemRsp{} }
func (m *AddSaleitemRsp) String() string { return proto.CompactTextString(m) }
func (*AddSaleitemRsp) ProtoMessage()    {}
func (*AddSaleitemRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_983657353a4bf784, []int{1}
}

func (m *AddSaleitemRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSaleitemRsp.Unmarshal(m, b)
}
func (m *AddSaleitemRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSaleitemRsp.Marshal(b, m, deterministic)
}
func (m *AddSaleitemRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSaleitemRsp.Merge(m, src)
}
func (m *AddSaleitemRsp) XXX_Size() int {
	return xxx_messageInfo_AddSaleitemRsp.Size(m)
}
func (m *AddSaleitemRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSaleitemRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AddSaleitemRsp proto.InternalMessageInfo

type GetBuyitemsByEmailReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBuyitemsByEmailReq) Reset()         { *m = GetBuyitemsByEmailReq{} }
func (m *GetBuyitemsByEmailReq) String() string { return proto.CompactTextString(m) }
func (*GetBuyitemsByEmailReq) ProtoMessage()    {}
func (*GetBuyitemsByEmailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_983657353a4bf784, []int{2}
}

func (m *GetBuyitemsByEmailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuyitemsByEmailReq.Unmarshal(m, b)
}
func (m *GetBuyitemsByEmailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuyitemsByEmailReq.Marshal(b, m, deterministic)
}
func (m *GetBuyitemsByEmailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuyitemsByEmailReq.Merge(m, src)
}
func (m *GetBuyitemsByEmailReq) XXX_Size() int {
	return xxx_messageInfo_GetBuyitemsByEmailReq.Size(m)
}
func (m *GetBuyitemsByEmailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuyitemsByEmailReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuyitemsByEmailReq proto.InternalMessageInfo

func (m *GetBuyitemsByEmailReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Item struct {
	Itemname             string   `protobuf:"bytes,1,opt,name=itemname,proto3" json:"itemname,omitempty"`
	Price                float32  `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Crtime               string   `protobuf:"bytes,3,opt,name=crtime,proto3" json:"crtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_983657353a4bf784, []int{3}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetItemname() string {
	if m != nil {
		return m.Itemname
	}
	return ""
}

func (m *Item) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetCrtime() string {
	if m != nil {
		return m.Crtime
	}
	return ""
}

type GetBuyitemsByEmailRsp struct {
	Uname                string   `protobuf:"bytes,1,opt,name=uname,proto3" json:"uname,omitempty"`
	Items                []*Item  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBuyitemsByEmailRsp) Reset()         { *m = GetBuyitemsByEmailRsp{} }
func (m *GetBuyitemsByEmailRsp) String() string { return proto.CompactTextString(m) }
func (*GetBuyitemsByEmailRsp) ProtoMessage()    {}
func (*GetBuyitemsByEmailRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_983657353a4bf784, []int{4}
}

func (m *GetBuyitemsByEmailRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuyitemsByEmailRsp.Unmarshal(m, b)
}
func (m *GetBuyitemsByEmailRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuyitemsByEmailRsp.Marshal(b, m, deterministic)
}
func (m *GetBuyitemsByEmailRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuyitemsByEmailRsp.Merge(m, src)
}
func (m *GetBuyitemsByEmailRsp) XXX_Size() int {
	return xxx_messageInfo_GetBuyitemsByEmailRsp.Size(m)
}
func (m *GetBuyitemsByEmailRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuyitemsByEmailRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuyitemsByEmailRsp proto.InternalMessageInfo

func (m *GetBuyitemsByEmailRsp) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

func (m *GetBuyitemsByEmailRsp) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetAllBuyitemsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllBuyitemsReq) Reset()         { *m = GetAllBuyitemsReq{} }
func (m *GetAllBuyitemsReq) String() string { return proto.CompactTextString(m) }
func (*GetAllBuyitemsReq) ProtoMessage()    {}
func (*GetAllBuyitemsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_983657353a4bf784, []int{5}
}

func (m *GetAllBuyitemsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllBuyitemsReq.Unmarshal(m, b)
}
func (m *GetAllBuyitemsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllBuyitemsReq.Marshal(b, m, deterministic)
}
func (m *GetAllBuyitemsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllBuyitemsReq.Merge(m, src)
}
func (m *GetAllBuyitemsReq) XXX_Size() int {
	return xxx_messageInfo_GetAllBuyitemsReq.Size(m)
}
func (m *GetAllBuyitemsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllBuyitemsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllBuyitemsReq proto.InternalMessageInfo

type BuyItem struct {
	Uname                string   `protobuf:"bytes,1,opt,name=uname,proto3" json:"uname,omitempty"`
	Itemname             string   `protobuf:"bytes,2,opt,name=itemname,proto3" json:"itemname,omitempty"`
	Price                float32  `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Crtime               string   `protobuf:"bytes,4,opt,name=crtime,proto3" json:"crtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyItem) Reset()         { *m = BuyItem{} }
func (m *BuyItem) String() string { return proto.CompactTextString(m) }
func (*BuyItem) ProtoMessage()    {}
func (*BuyItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_983657353a4bf784, []int{6}
}

func (m *BuyItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyItem.Unmarshal(m, b)
}
func (m *BuyItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyItem.Marshal(b, m, deterministic)
}
func (m *BuyItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyItem.Merge(m, src)
}
func (m *BuyItem) XXX_Size() int {
	return xxx_messageInfo_BuyItem.Size(m)
}
func (m *BuyItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyItem.DiscardUnknown(m)
}

var xxx_messageInfo_BuyItem proto.InternalMessageInfo

func (m *BuyItem) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

func (m *BuyItem) GetItemname() string {
	if m != nil {
		return m.Itemname
	}
	return ""
}

func (m *BuyItem) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BuyItem) GetCrtime() string {
	if m != nil {
		return m.Crtime
	}
	return ""
}

type GetAllBuyitemsRsp struct {
	Buyitems             []*BuyItem `protobuf:"bytes,1,rep,name=buyitems,proto3" json:"buyitems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAllBuyitemsRsp) Reset()         { *m = GetAllBuyitemsRsp{} }
func (m *GetAllBuyitemsRsp) String() string { return proto.CompactTextString(m) }
func (*GetAllBuyitemsRsp) ProtoMessage()    {}
func (*GetAllBuyitemsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_983657353a4bf784, []int{7}
}

func (m *GetAllBuyitemsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllBuyitemsRsp.Unmarshal(m, b)
}
func (m *GetAllBuyitemsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllBuyitemsRsp.Marshal(b, m, deterministic)
}
func (m *GetAllBuyitemsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllBuyitemsRsp.Merge(m, src)
}
func (m *GetAllBuyitemsRsp) XXX_Size() int {
	return xxx_messageInfo_GetAllBuyitemsRsp.Size(m)
}
func (m *GetAllBuyitemsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllBuyitemsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllBuyitemsRsp proto.InternalMessageInfo

func (m *GetAllBuyitemsRsp) GetBuyitems() []*BuyItem {
	if m != nil {
		return m.Buyitems
	}
	return nil
}

//message可以单独作为结构体传入
type Itemdemo struct {
	Itemdemo             *Item    `protobuf:"bytes,1,opt,name=itemdemo,proto3" json:"itemdemo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Itemdemo) Reset()         { *m = Itemdemo{} }
func (m *Itemdemo) String() string { return proto.CompactTextString(m) }
func (*Itemdemo) ProtoMessage()    {}
func (*Itemdemo) Descriptor() ([]byte, []int) {
	return fileDescriptor_983657353a4bf784, []int{8}
}

func (m *Itemdemo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Itemdemo.Unmarshal(m, b)
}
func (m *Itemdemo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Itemdemo.Marshal(b, m, deterministic)
}
func (m *Itemdemo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Itemdemo.Merge(m, src)
}
func (m *Itemdemo) XXX_Size() int {
	return xxx_messageInfo_Itemdemo.Size(m)
}
func (m *Itemdemo) XXX_DiscardUnknown() {
	xxx_messageInfo_Itemdemo.DiscardUnknown(m)
}

var xxx_messageInfo_Itemdemo proto.InternalMessageInfo

func (m *Itemdemo) GetItemdemo() *Item {
	if m != nil {
		return m.Itemdemo
	}
	return nil
}

func init() {
	proto.RegisterType((*AddSaleitemReq)(nil), "pb.AddSaleitemReq")
	proto.RegisterType((*AddSaleitemRsp)(nil), "pb.AddSaleitemRsp")
	proto.RegisterType((*GetBuyitemsByEmailReq)(nil), "pb.GetBuyitemsByEmailReq")
	proto.RegisterType((*Item)(nil), "pb.Item")
	proto.RegisterType((*GetBuyitemsByEmailRsp)(nil), "pb.GetBuyitemsByEmailRsp")
	proto.RegisterType((*GetAllBuyitemsReq)(nil), "pb.GetAllBuyitemsReq")
	proto.RegisterType((*BuyItem)(nil), "pb.BuyItem")
	proto.RegisterType((*GetAllBuyitemsRsp)(nil), "pb.GetAllBuyitemsRsp")
	proto.RegisterType((*Itemdemo)(nil), "pb.Itemdemo")
}

func init() { proto.RegisterFile("sale.proto", fileDescriptor_983657353a4bf784) }

var fileDescriptor_983657353a4bf784 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xfd, 0x25, 0xfd, 0xf3, 0x4b, 0xa7, 0x50, 0x74, 0xb4, 0x12, 0x73, 0x90, 0xb2, 0x08, 0xf6,
	0x62, 0x91, 0x0a, 0x9e, 0x3c, 0xd8, 0x82, 0x14, 0x41, 0x41, 0xb6, 0x17, 0xaf, 0x49, 0x33, 0x87,
	0x40, 0x62, 0xb7, 0x49, 0x2a, 0xf4, 0x83, 0xfa, 0x7d, 0x64, 0x76, 0x63, 0xc9, 0xd2, 0xf4, 0xe0,
	0x2d, 0xef, 0xcd, 0xec, 0x7b, 0x6f, 0x76, 0x36, 0x00, 0x45, 0x98, 0xd2, 0x44, 0xe5, 0xeb, 0x72,
	0x8d, 0xae, 0x8a, 0xc4, 0x07, 0x0c, 0x66, 0x71, 0xbc, 0x0c, 0x53, 0x4a, 0x4a, 0xca, 0x24, 0x6d,
	0xf0, 0x1c, 0x3a, 0x94, 0x85, 0x49, 0xea, 0x3b, 0x23, 0x67, 0xdc, 0x93, 0x06, 0x60, 0x00, 0x1e,
	0x37, 0x7c, 0x86, 0x19, 0xf9, 0xae, 0x2e, 0xec, 0x31, 0x9f, 0x50, 0x79, 0xb2, 0x22, 0xbf, 0x35,
	0x72, 0xc6, 0xae, 0x34, 0x40, 0x9c, 0xd8, 0xca, 0x85, 0x12, 0xb7, 0x30, 0x5c, 0x50, 0x39, 0xdf,
	0xee, 0x98, 0x28, 0xe6, 0xbb, 0x67, 0x56, 0x3e, 0x6a, 0x29, 0xde, 0xa1, 0xfd, 0x52, 0x52, 0x66,
	0x59, 0x3b, 0xc7, 0xac, 0xdd, 0x9a, 0x35, 0x5e, 0x40, 0x77, 0x95, 0x97, 0x49, 0x66, 0x12, 0xf5,
	0x64, 0x85, 0xc4, 0x5b, 0x63, 0x80, 0x42, 0xb1, 0xcc, 0xb6, 0xa6, 0x6f, 0x00, 0x5e, 0x41, 0x47,
	0x37, 0xfa, 0xee, 0xa8, 0x35, 0xee, 0x4f, 0xbd, 0x89, 0x8a, 0x26, 0x9c, 0x48, 0x1a, 0x5a, 0x9c,
	0xc1, 0xe9, 0x82, 0xca, 0x59, 0x9a, 0xfe, 0x2a, 0x4a, 0xda, 0x88, 0x04, 0xfe, 0xcf, 0xb7, 0x3b,
	0x1d, 0xbc, 0x59, 0xf5, 0xcf, 0x37, 0x59, 0x1b, 0xa7, 0x6d, 0x8d, 0xf3, 0x78, 0xe0, 0x5f, 0x28,
	0xbc, 0x01, 0x2f, 0xaa, 0xa0, 0xef, 0xe8, 0xdc, 0x7d, 0xce, 0x5d, 0x65, 0x92, 0xfb, 0xa2, 0xb8,
	0x03, 0x8f, 0x99, 0x98, 0xb2, 0x35, 0x5e, 0x9b, 0x4c, 0xfc, 0xad, 0xc3, 0xd6, 0x87, 0xdd, 0x57,
	0xa6, 0xdf, 0x0e, 0xf4, 0x79, 0x9f, 0x4b, 0xca, 0xbf, 0x38, 0xd7, 0x03, 0xc0, 0x2c, 0x8e, 0x2b,
	0x73, 0x44, 0x3e, 0x61, 0xbf, 0xa5, 0xe0, 0x80, 0x2b, 0x94, 0xf8, 0x87, 0xaf, 0x80, 0x87, 0x6b,
	0xc0, 0x4b, 0xee, 0x6d, 0x7c, 0x1f, 0xc1, 0xb1, 0x92, 0x56, 0x7b, 0x82, 0x81, 0x7d, 0x0b, 0x38,
	0xac, 0xda, 0xed, 0xcd, 0x04, 0x4d, 0x34, 0x2b, 0x44, 0x5d, 0xfd, 0x3b, 0xdc, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x1f, 0x4b, 0x90, 0x41, 0x1c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SaleService service

type SaleServiceClient interface {
	//新增用户购买信息
	AddBuyitem(ctx context.Context, in *AddSaleitemReq, opts ...client.CallOption) (*AddSaleitemRsp, error)
	//通过email查询某用户购买信息
	GetBuyitemsByEmail(ctx context.Context, in *GetBuyitemsByEmailReq, opts ...client.CallOption) (*GetBuyitemsByEmailRsp, error)
	//获取所有购买信息
	GetAllBuyitems(ctx context.Context, in *GetAllBuyitemsReq, opts ...client.CallOption) (*GetAllBuyitemsRsp, error)
}

type saleServiceClient struct {
	c           client.Client
	serviceName string
}

func NewSaleServiceClient(serviceName string, c client.Client) SaleServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "pb"
	}
	return &saleServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *saleServiceClient) AddBuyitem(ctx context.Context, in *AddSaleitemReq, opts ...client.CallOption) (*AddSaleitemRsp, error) {
	req := c.c.NewRequest(c.serviceName, "SaleService.AddBuyitem", in)
	out := new(AddSaleitemRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleServiceClient) GetBuyitemsByEmail(ctx context.Context, in *GetBuyitemsByEmailReq, opts ...client.CallOption) (*GetBuyitemsByEmailRsp, error) {
	req := c.c.NewRequest(c.serviceName, "SaleService.GetBuyitemsByEmail", in)
	out := new(GetBuyitemsByEmailRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleServiceClient) GetAllBuyitems(ctx context.Context, in *GetAllBuyitemsReq, opts ...client.CallOption) (*GetAllBuyitemsRsp, error) {
	req := c.c.NewRequest(c.serviceName, "SaleService.GetAllBuyitems", in)
	out := new(GetAllBuyitemsRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SaleService service

type SaleServiceHandler interface {
	//新增用户购买信息
	AddBuyitem(context.Context, *AddSaleitemReq, *AddSaleitemRsp) error
	//通过email查询某用户购买信息
	GetBuyitemsByEmail(context.Context, *GetBuyitemsByEmailReq, *GetBuyitemsByEmailRsp) error
	//获取所有购买信息
	GetAllBuyitems(context.Context, *GetAllBuyitemsReq, *GetAllBuyitemsRsp) error
}

func RegisterSaleServiceHandler(s server.Server, hdlr SaleServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&SaleService{hdlr}, opts...))
}

type SaleService struct {
	SaleServiceHandler
}

func (h *SaleService) AddBuyitem(ctx context.Context, in *AddSaleitemReq, out *AddSaleitemRsp) error {
	return h.SaleServiceHandler.AddBuyitem(ctx, in, out)
}

func (h *SaleService) GetBuyitemsByEmail(ctx context.Context, in *GetBuyitemsByEmailReq, out *GetBuyitemsByEmailRsp) error {
	return h.SaleServiceHandler.GetBuyitemsByEmail(ctx, in, out)
}

func (h *SaleService) GetAllBuyitems(ctx context.Context, in *GetAllBuyitemsReq, out *GetAllBuyitemsRsp) error {
	return h.SaleServiceHandler.GetAllBuyitems(ctx, in, out)
}
