// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegistAccountReq struct {
	Uname                string   `protobuf:"bytes,1,opt,name=uname,proto3" json:"uname,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistAccountReq) Reset()         { *m = RegistAccountReq{} }
func (m *RegistAccountReq) String() string { return proto.CompactTextString(m) }
func (*RegistAccountReq) ProtoMessage()    {}
func (*RegistAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *RegistAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistAccountReq.Unmarshal(m, b)
}
func (m *RegistAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistAccountReq.Marshal(b, m, deterministic)
}
func (m *RegistAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistAccountReq.Merge(m, src)
}
func (m *RegistAccountReq) XXX_Size() int {
	return xxx_messageInfo_RegistAccountReq.Size(m)
}
func (m *RegistAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegistAccountReq proto.InternalMessageInfo

func (m *RegistAccountReq) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

func (m *RegistAccountReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegistAccountReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegistAccountRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistAccountRsp) Reset()         { *m = RegistAccountRsp{} }
func (m *RegistAccountRsp) String() string { return proto.CompactTextString(m) }
func (*RegistAccountRsp) ProtoMessage()    {}
func (*RegistAccountRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *RegistAccountRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistAccountRsp.Unmarshal(m, b)
}
func (m *RegistAccountRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistAccountRsp.Marshal(b, m, deterministic)
}
func (m *RegistAccountRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistAccountRsp.Merge(m, src)
}
func (m *RegistAccountRsp) XXX_Size() int {
	return xxx_messageInfo_RegistAccountRsp.Size(m)
}
func (m *RegistAccountRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistAccountRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegistAccountRsp proto.InternalMessageInfo

type GetUinfoByEmailReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUinfoByEmailReq) Reset()         { *m = GetUinfoByEmailReq{} }
func (m *GetUinfoByEmailReq) String() string { return proto.CompactTextString(m) }
func (*GetUinfoByEmailReq) ProtoMessage()    {}
func (*GetUinfoByEmailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GetUinfoByEmailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUinfoByEmailReq.Unmarshal(m, b)
}
func (m *GetUinfoByEmailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUinfoByEmailReq.Marshal(b, m, deterministic)
}
func (m *GetUinfoByEmailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUinfoByEmailReq.Merge(m, src)
}
func (m *GetUinfoByEmailReq) XXX_Size() int {
	return xxx_messageInfo_GetUinfoByEmailReq.Size(m)
}
func (m *GetUinfoByEmailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUinfoByEmailReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUinfoByEmailReq proto.InternalMessageInfo

func (m *GetUinfoByEmailReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUinfoByEmailRsp struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uname                string   `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Crtime               string   `protobuf:"bytes,4,opt,name=crtime,proto3" json:"crtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUinfoByEmailRsp) Reset()         { *m = GetUinfoByEmailRsp{} }
func (m *GetUinfoByEmailRsp) String() string { return proto.CompactTextString(m) }
func (*GetUinfoByEmailRsp) ProtoMessage()    {}
func (*GetUinfoByEmailRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *GetUinfoByEmailRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUinfoByEmailRsp.Unmarshal(m, b)
}
func (m *GetUinfoByEmailRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUinfoByEmailRsp.Marshal(b, m, deterministic)
}
func (m *GetUinfoByEmailRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUinfoByEmailRsp.Merge(m, src)
}
func (m *GetUinfoByEmailRsp) XXX_Size() int {
	return xxx_messageInfo_GetUinfoByEmailRsp.Size(m)
}
func (m *GetUinfoByEmailRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUinfoByEmailRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUinfoByEmailRsp proto.InternalMessageInfo

func (m *GetUinfoByEmailRsp) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetUinfoByEmailRsp) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

func (m *GetUinfoByEmailRsp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUinfoByEmailRsp) GetCrtime() string {
	if m != nil {
		return m.Crtime
	}
	return ""
}

type GetAllUinfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllUinfoReq) Reset()         { *m = GetAllUinfoReq{} }
func (m *GetAllUinfoReq) String() string { return proto.CompactTextString(m) }
func (*GetAllUinfoReq) ProtoMessage()    {}
func (*GetAllUinfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *GetAllUinfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUinfoReq.Unmarshal(m, b)
}
func (m *GetAllUinfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUinfoReq.Marshal(b, m, deterministic)
}
func (m *GetAllUinfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUinfoReq.Merge(m, src)
}
func (m *GetAllUinfoReq) XXX_Size() int {
	return xxx_messageInfo_GetAllUinfoReq.Size(m)
}
func (m *GetAllUinfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUinfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUinfoReq proto.InternalMessageInfo

type GetAllUinfoRsp struct {
	Alluinfo             []*GetUinfoByEmailRsp `protobuf:"bytes,1,rep,name=alluinfo,proto3" json:"alluinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetAllUinfoRsp) Reset()         { *m = GetAllUinfoRsp{} }
func (m *GetAllUinfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetAllUinfoRsp) ProtoMessage()    {}
func (*GetAllUinfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *GetAllUinfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllUinfoRsp.Unmarshal(m, b)
}
func (m *GetAllUinfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllUinfoRsp.Marshal(b, m, deterministic)
}
func (m *GetAllUinfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllUinfoRsp.Merge(m, src)
}
func (m *GetAllUinfoRsp) XXX_Size() int {
	return xxx_messageInfo_GetAllUinfoRsp.Size(m)
}
func (m *GetAllUinfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllUinfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllUinfoRsp proto.InternalMessageInfo

func (m *GetAllUinfoRsp) GetAlluinfo() []*GetUinfoByEmailRsp {
	if m != nil {
		return m.Alluinfo
	}
	return nil
}

func init() {
	proto.RegisterType((*RegistAccountReq)(nil), "pb.RegistAccountReq")
	proto.RegisterType((*RegistAccountRsp)(nil), "pb.RegistAccountRsp")
	proto.RegisterType((*GetUinfoByEmailReq)(nil), "pb.GetUinfoByEmailReq")
	proto.RegisterType((*GetUinfoByEmailRsp)(nil), "pb.GetUinfoByEmailRsp")
	proto.RegisterType((*GetAllUinfoReq)(nil), "pb.GetAllUinfoReq")
	proto.RegisterType((*GetAllUinfoRsp)(nil), "pb.GetAllUinfoRsp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x3d, 0x4f, 0xc3, 0x30,
	0x14, 0x6c, 0x52, 0x5a, 0x95, 0x57, 0x51, 0xaa, 0xa7, 0xaa, 0x8a, 0x32, 0x55, 0x9e, 0x2a, 0x86,
	0x0e, 0x65, 0x60, 0x62, 0x28, 0x1f, 0xea, 0x6e, 0xd4, 0x85, 0x2d, 0x4d, 0x1e, 0x60, 0x29, 0x1f,
	0x8e, 0xed, 0x80, 0xf8, 0x8b, 0xfc, 0x2a, 0x14, 0x27, 0x2a, 0x69, 0x12, 0xc6, 0x3b, 0xdf, 0xbd,
	0xbb, 0x67, 0x1b, 0xa0, 0xd0, 0xa4, 0x36, 0x52, 0x65, 0x26, 0x43, 0x57, 0x1e, 0xd9, 0x2b, 0xcc,
	0x39, 0xbd, 0x0b, 0x6d, 0x76, 0x61, 0x98, 0x15, 0xa9, 0xe1, 0x94, 0xe3, 0x02, 0x46, 0x45, 0x1a,
	0x24, 0xe4, 0x39, 0x2b, 0x67, 0x7d, 0xc9, 0x2b, 0x80, 0x3e, 0x4c, 0x64, 0xa0, 0xf5, 0x57, 0xa6,
	0x22, 0xcf, 0xb5, 0x07, 0x27, 0x5c, 0x3a, 0x28, 0x09, 0x44, 0xec, 0x0d, 0x2b, 0x87, 0x05, 0x0c,
	0xdb, 0xb3, 0xb5, 0x64, 0x37, 0x80, 0x7b, 0x32, 0x07, 0x91, 0xbe, 0x65, 0x0f, 0xdf, 0xcf, 0xa5,
	0xac, 0x4e, 0xac, 0xfc, 0x4e, 0xd3, 0xff, 0xd1, 0xd5, 0x6a, 0x89, 0x33, 0x70, 0x45, 0x64, 0x85,
	0x23, 0xee, 0x8a, 0xe8, 0xaf, 0xad, 0xdb, 0x6c, 0xdb, 0xdb, 0x08, 0x97, 0x30, 0x0e, 0x95, 0x11,
	0x09, 0x79, 0x17, 0x96, 0xae, 0x11, 0x9b, 0xc3, 0x6c, 0x4f, 0x66, 0x17, 0xc7, 0x36, 0x8c, 0x53,
	0xce, 0x9e, 0xce, 0x19, 0x2d, 0x71, 0x0b, 0x93, 0x20, 0x8e, 0x8b, 0x12, 0x7a, 0xce, 0x6a, 0xb8,
	0x9e, 0x6e, 0x97, 0x1b, 0x79, 0xdc, 0x74, 0x1b, 0xf2, 0x93, 0x6e, 0xfb, 0xe3, 0xc0, 0xf4, 0xa0,
	0x49, 0xbd, 0x90, 0xfa, 0x14, 0x21, 0xe1, 0x3d, 0x5c, 0x9d, 0xdd, 0x08, 0x2e, 0xca, 0x11, 0xed,
	0x07, 0xf0, 0x7b, 0x58, 0x2d, 0xd9, 0x00, 0x1f, 0xe1, 0xba, 0x15, 0x87, 0xbd, 0x1d, 0x28, 0xf7,
	0xff, 0xe9, 0xc6, 0x06, 0x78, 0x07, 0xd3, 0xc6, 0x66, 0x88, 0xb5, 0xb0, 0xb1, 0xbc, 0xdf, 0xe1,
	0x4a, 0xe3, 0x71, 0x6c, 0x7f, 0xcd, 0xed, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0x76, 0x38,
	0x19, 0x43, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserServiceClient interface {
	//注册用户
	RegistAccount(ctx context.Context, in *RegistAccountReq, opts ...client.CallOption) (*RegistAccountRsp, error)
	//通过email查询某用户信息
	GetUinfoByEmail(ctx context.Context, in *GetUinfoByEmailReq, opts ...client.CallOption) (*GetUinfoByEmailRsp, error)
	//获取所有用户
	GetAllUinfo(ctx context.Context, in *GetAllUinfoReq, opts ...client.CallOption) (*GetAllUinfoRsp, error)
}

type userServiceClient struct {
	c           client.Client
	serviceName string
}

func NewUserServiceClient(serviceName string, c client.Client) UserServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "pb"
	}
	return &userServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceClient) RegistAccount(ctx context.Context, in *RegistAccountReq, opts ...client.CallOption) (*RegistAccountRsp, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.RegistAccount", in)
	out := new(RegistAccountRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUinfoByEmail(ctx context.Context, in *GetUinfoByEmailReq, opts ...client.CallOption) (*GetUinfoByEmailRsp, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.GetUinfoByEmail", in)
	out := new(GetUinfoByEmailRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetAllUinfo(ctx context.Context, in *GetAllUinfoReq, opts ...client.CallOption) (*GetAllUinfoRsp, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.GetAllUinfo", in)
	out := new(GetAllUinfoRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	//注册用户
	RegistAccount(context.Context, *RegistAccountReq, *RegistAccountRsp) error
	//通过email查询某用户信息
	GetUinfoByEmail(context.Context, *GetUinfoByEmailReq, *GetUinfoByEmailRsp) error
	//获取所有用户
	GetAllUinfo(context.Context, *GetAllUinfoReq, *GetAllUinfoRsp) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserService{hdlr}, opts...))
}

type UserService struct {
	UserServiceHandler
}

func (h *UserService) RegistAccount(ctx context.Context, in *RegistAccountReq, out *RegistAccountRsp) error {
	return h.UserServiceHandler.RegistAccount(ctx, in, out)
}

func (h *UserService) GetUinfoByEmail(ctx context.Context, in *GetUinfoByEmailReq, out *GetUinfoByEmailRsp) error {
	return h.UserServiceHandler.GetUinfoByEmail(ctx, in, out)
}

func (h *UserService) GetAllUinfo(ctx context.Context, in *GetAllUinfoReq, out *GetAllUinfoRsp) error {
	return h.UserServiceHandler.GetAllUinfo(ctx, in, out)
}
